name: Snyk Image Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Pull image
        run: docker pull nginx:latest

      - name: Scan image
        continue-on-error: true
        run: snyk container test nginx:latest

      - name: Generate JSON report
        continue-on-error: true
        run: snyk container test nginx:latest --json > snyk-report.json

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

      - name: Monitor
        run: snyk container monitor nginx:latest
