name: Snyk Image Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Pull image
        run: docker pull nginx:latest

      - name: Scan image
        continue-on-error: true
        run: snyk container test nginx:latest

      - name: Monitor
        run: snyk container monitor nginx:latest
